// SPDX-License-Identifier: MIT

pragma solidity >=0.8.0 <0.9.0;

import "../WitOracle.sol";

/// @title The Wit/Randomness appliance interface.
/// @author Witnet Foundation.
interface IWitRandomness {
   
    /// @notice Returns amount of wei required to be paid as a fee when requesting randomization with a 
    /// transaction gas price as the one given.
    function estimateRandomizeFee(uint256 evmGasPrice) external view returns (uint256);

    /// @notice Retrieves the result of keccak256-hashing the given block number with the randomness value 
    /// generated by the Witnet blockchain in response to the first non-failing randomize request solved 
    /// after such block number.
    ///
    /// @dev Reverts if:
    ///    i.   no `randomize()` was queried on neither the given block, nor afterwards.
    ///    ii.  the first non-failing `randomize()` request found on or after the given block is not solved yet.
    ///    iii. all `randomize()` requests that took place on or after the given block were solved with errors.
    ///
    /// @param blockNumber Block number from which the search will start.
    function fetchRandomnessAfter(uint256 blockNumber) external view returns (bytes32);

    /// @notice Retrieves the actual random value, unique hash and timestamp of the witnessing commit/reveal act 
    /// that took place in the Witnet blockchain in response to the first non-failing randomize query
    /// solved after the given block number.
    /// @dev Reverts if:
    ///    i.   no `randomize()` was queried on neither the given block, nor afterwards.
    ///    ii.  the first non-failing `randomize()` request found on or after the given block is not solved yet.
    ///    iii. all `randomize()` requests that took place on or after the given block were solved with errors.
    /// @param blockNumber Block number from which the search will start.
    /// @return witnetQueryUUID Identifier of the query, posted from this contract, that ultimately solved randomness.
    /// @return witnetTimestamp Timestamp at which the randomness value was generated by the Witnet blockchain.
    /// @return witnetDrTxHash Hash of the witnessing commit/reveal act that took place on the Witnet blockchain.
    /// @return evmFinalityBlock EVM block number at which the generated randomness can be considered to be final.
    function fetchRandomnessAfterProof(uint256 blockNumber) external view returns (
            bytes32 witnetQueryUUID,
            Witnet.Timestamp witnetTimestamp,
            Witnet.TransactionHash witnetDrTxHash,
            uint256 evmFinalityBlock
        ); 

    /// @notice Returns last block number on which a randomize was queried.
    function getLastRandomizeBlock() external view returns (uint256);

    /// @notice Retrieves metadata related to the randomize request that got queried to the `WitOracle` contract 
    /// on the specified block number, if any.
    /// @dev Returns zero values if no randomize request was actually queried on the specified block number.
    /// @param blockNumber Block number from which the search will start.
    /// @return witOracleQueryId Identifier of the underlying Wit/Oracle query created on the specified block number. 
    /// @return prevRandomizeBlock Block number in which a randomize request got queried just before this one. 0 if none.
    /// @return nextRandomizeBlock Block number in which a randomize request got queried just after this one, 0 if none.
    function getRandomizeData(uint256 blockNumber) external view returns (
            uint256 witOracleQueryId,
            uint256 prevRandomizeBlock,
            uint256 nextRandomizeBlock
        );

    /// @notice Returns security and liveness parameters required to the Witnet blockchain 
    /// when solving randomness requests, if no others are specified.
    /// @param witCommitteeSize Number of Wit/Oracle nodes contributing to unbiased randomness.
    /// @param witUnitaryReward Minimum amount of fees in $nanoWIT to be paid on the Witnet blockchain
    function getRandomizeDefaultParams() 
        external view returns (
            uint16 witCommitteeSize,
            uint64 witUnitaryReward
        );
    
    /// @notice Returns the number of the next block in which a randomize request was posted after the given one. 
    /// @param blockNumber Block number from which the search will start.
    /// @return Number of the first block found after the given one, or `0` otherwise.
    function getRandomizeNextBlock(uint256 blockNumber) external view returns (uint256); 

    /// @notice Returns the number of the previous block in which a randomize request was posted before the given one.
    /// @param blockNumber Block number from which the search will start.
    /// @return First block found before the given one, or `0` otherwise.
    function getRandomizePrevBlock(uint256 blockNumber) external view returns (uint256);

    /// @notice Returns the bytecode of the Radon Request used for solving
    /// randomness requests on the Witnet blockchain.
    function getRandomizeRadonBytecode() external view returns (bytes memory);

    /// @notice Returns the unique identifier of the Radon Request used for solving 
    /// request randomness requests on the Witnet blockchain.
    function getRandomizeRadonHash() external view returns (Witnet.RadonHash);

    /// @notice Returns status of the first non-errored randomize request queried on or after the given block number.
    ///  - 0 -> Void: no randomize request was actually queried on or after the given block number.
    ///  - 1 -> Awaiting: a randomize request was found but it's not yet solved by the Wit/Oracle.
    ///  - 2 -> Ready: a successfull randomize value was reported and is ready to be read.
    ///  - 3 -> Error: all attempted randomize requests at or after the given block were solved with errors.
    ///  - 4 -> Finalizing: a randomize result was relayed already but cannot yet be considered to be final.
    function getRandomizeStatus(uint256 blockNumber) external view returns (RandomizeStatus);    
        enum RandomizeStatus {
            Void,
            Awaiting,
            Ready,
            Error,
            Finalizing
        }
    function getRandomizeStatusDescription(uint256 blockNumber) external view returns (string memory);

    /// @notice Returns `true` only if a successfull resolution from the Witnet blockchain is found for the 
    /// first non-failing randomize request posted on or after the given block number.
    function isRandomized(uint256 blockNumber) external view returns (bool);

    /// @notice Generates a pseudo-random number uniformly distributed within the range [0 .. _range), by using 
    /// the given `nonce` and the randomness returned by `fetchRandomnessAfter(blockNumber)`. 
    /// @dev Fails under same conditions as `fetchRandomnessAfter(uint256)` does.
    /// @param range Range within which the uniformly-distributed random number will be generated.
    /// @param nonce Nonce value enabling multiple random numbers from the same randomness value.
    /// @param blockNumber Block number from which the search for the first randomize request solved aftewards will start.
    function random(uint32 range, uint256 nonce, uint256 blockNumber) external view returns (uint32);

    /// @notice Requests the Witnet blockchain to generate an unbiased 256-bit random seed.
    /// @dev Only one randomize request per block will get ultimately relayed to the Witnet blockchain.
    /// @return EVM funds actually paid as randomize fee.
    function randomize() external payable returns (uint256);

    /// @notice Requests the Witnet blockchain to generate an unbiased 256-bit random seed, complying with 
    /// the given SLA parameters.
    /// @dev Only one randomize request per block will get ultimately relayed to Witnet. Reverts if the
    /// given parameters do not comply with the `IWitRandomnessAdmin.witOracleRequiredParams()` limits.
    /// @param witnetCommitteeSize Number of witnesses that will contribute to generate unbiased randomness.
    /// @param witnetInclusionFees Minimum amount of nanoWits to be paid for including request on the Witnet blockchain.
    /// @return Funds actually paid as randomize fee.
    function randomize(uint16 witnetCommitteeSize, uint64 witnetInclusionFees) external payable returns (uint256);
}
